baseURL = 'https://web.infenlaces.com/dwes'
languageCode = 'es-es'
title = 'Presentación del móldulo'

disableKinds = ["sitemap", "RSS"]
# theme = "moon"
# themesDir = "."


enableEmoji = true

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true


# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
codeFences = false  # use highlight.js
# codeFences = true  # use hugo highlighting at compile time
style = "zenburn"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
reveal_options = '''
{
    "plugins": [ RevealNotes ]
}
'''

# used in content/template-example
[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"









 [module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    disable = false
